# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DBTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FMDB'

  # Pods for DBTest

  target 'DBTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DBTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
